#配置数据源信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comments?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12121

#配置jpa


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization.indent_output: true